### PR TITLE
linux-mainline: Update base image and fix build failures

### PR DESCRIPTION
**Pull request by alistair23**

### CODE REVIEW

**Comment by Eeems** [comment]
```
[   DEBUG] toltec.builder: build(): In file included from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/sysroot/usr/include/features.h:489,
[   DEBUG] toltec.builder: build(): from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/sysroot/usr/include/bits/libc-header-start.h:33,
[   DEBUG] toltec.builder: build(): from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/sysroot/usr/include/stdio.h:27,
[   DEBUG] toltec.builder: build(): from certs/extract-cert.c:15:
[   DEBUG] toltec.builder: build(): /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/sysroot/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-soft.h: No such file or directory
[   DEBUG] toltec.builder: build(): 7 | # include <gnu/stubs-soft.h>
[   DEBUG] toltec.builder: build(): |           ^~~~~~~~~~~~~~~~~~
[   DEBUG] toltec.builder: build(): compilation terminated.
```

**Comment by Eeems** [comment]
This might be due to trying to use the system pkgconfig instead of the toolchain version.

**Comment by alistair23** [comment]
Fixed! (Hopefully)

**Comment by alistair23** [comment]
Anything else for me to do here?

**Comment by alistair23** [comment]
Ping!

**Comment by Eeems** [comment]
Just the standard testing of the package build in the pipeline on 2.15 and 3.3.2 is required. I don't have capacity right now to do any testing.

**Comment by Eeems** [comment]
So one issue on 3.3.2 is that this kernel doesn't provide uinput, which breaks compatibility with the current version of oxide as well as keyd (#744).

@alistair23 we have three options here to resolve this:

1. Update the kernel to include uinput
2. Mark this package as conflicting with oxide, and we update #744 to indicate it conflicts with linux-mainline
3. Add a known issue to the list that anything that depends on uinput will not work, and list keyd and oxide as examples

**Comment by Eeems** [comment]
@alistair23 since this hasn't been updated, I'm going to move this to draft until you pick it back up.

**Comment by alistair23** [comment]
I just added uinput support

**Comment by Eeems** [comment]
@alistair23 it looks like you undid the version update when you added uinput?

**Comment by alistair23** [comment]
Fixed!

**Comment by Eeems** [comment]
I'm going to try to get to testing this and getting it merged soon.

**Review by Eeems — APPROVED** [review]
